version: '3.8'

x-airflow-common: &airflow-common
  image: custom-airflow-veo:latest
  env_file:
    - .env
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./outputs:/opt/airflow/outputs
    - ./src:/opt/airflow/src
    - ./prompts:/opt/airflow/prompts
    - ~/.config/gcloud:/opt/airflow/.config/gcloud:ro
  depends_on:
    - postgres
  environment:
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__CORE__LOAD_EXAMPLES=False
    - AIRFLOW__CORE__FERNET_KEY=${AIRFLOW__CORE__FERNET_KEY}
    - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    - GOOGLE_APPLICATION_CREDENTIALS=/opt/airflow/.config/gcloud/application_default_credentials.json
    - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}
    - GOOGLE_CLOUD_LOCATION=${GOOGLE_CLOUD_LOCATION}
    - GCS_OUTPUT_BUCKET=${GCS_OUTPUT_BUCKET}
    - GOOGLE_GENAI_USE_VERTEXAI=${GOOGLE_GENAI_USE_VERTEXAI}
    - MAX_RETRIES=${MAX_RETRIES:-3}
    - BASE_DELAY=${BASE_DELAY:-5}
    - MAX_DELAY=${MAX_DELAY:-60}

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8081:8080"
    depends_on:
      - postgres
      - redis

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    depends_on:
      - postgres
      - redis

  prompt-manager:
    build: ./prompt_manager_ui
    ports:
      - "5001:5000"
    volumes:
      - ./prompt_manager_ui:/app
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  postgres_data:
  redis_data:
  logs:
  outputs:
  dags:
  src:
  prompts: 